sudo: false
language: ruby
cache:
  bundler: true
addons:
  postgresql: '9.4'
  # chrome: stable
rvm:
- 2.5.3
env:
  global:
  - SECRET_TOKEN=ebf574851882756b85824f66f5383b4cb4c61e211f017316a8e5
  - RACK_ENV=test
  - TEST_DATABASE_URL="postgres://127.0.0.1:5432/rotodo_test"

before_script:
- psql -c 'create database rotodo_test;' -U postgres
- sequel -m migrations postgres://postgres@localhost/rotodo_test
script:
- xvfb-run bundle exec rspec --format progress
